monitor=,preferred,auto,auto

# STYLE
source = ./styles/blocky-solid.conf

# START UP
exec-once = hyprpaper
exec-once = emacs --daemon
exec-once = gnome-setup

input {
    kb_layout = us,ru
    kb_variant = grp:win_space_toggle
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    accel_profile = flat
    touchpad {
        natural_scroll = 1
        scroll_factor = 0.5
    }

    sensitivity = 0
}

gestures {
    workspace_swipe = 1
}

general {
    layout = master
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    mfact = 0.5
    new_is_master = false
    inherit_fullscreen = false
}

gestures {
    workspace_swipe = off
}

device:chad_keyboard {
    kb_layout = us,ru
}

# WINDOW RULES
windowrule = tile, Spotify
windowrule = float, telegram-desktop
windowrule = float, REAPER
windowrule = float, xdg-desktop-portal-gtk
windowrule = workspace 4, Emacs
windowrule = workspace 5, Gimp
windowrule = workspace 5, DesktopEditors
windowrule = workspace 6, obs
windowrule = workspace 7, discord
windowrule = workspace 7, zoom
windowrule = workspace 8, telegram
windowrule = workspace 8, Spotify
windowrule = workspace 9, Brave

# KEY BINDINGS
$mainMod = SUPER

# Launchers
bind = $mainMod, Return, exec, kitty
bind = $mainMod SHIFT, Return, exec, rofi -show drun
bind = $mainMod, B, exec, brave
bind = $mainMod SHIFT, E, exec, emacsclient -c

# Controls
bind = $mainMod SHIFT, C, killactive, 
bind = $mainMod CTRL, Q, exit, 
bind = $mainMod SHIFT, Space, togglefloating, 
bind = $mainMod, F, fullscreen, 0

# Pulseaudio control
bind = $mainMod, up, exec, pamixer -i 5
bind = $mainMod, down, exec, pamixer -d 5
bind = $mainMod SHIFT, M, exec, pamixer -t

# Brightness control
bind = $mainMod SHIFT, up, exec, brightnessctl set 5%+
bind = $mainMod SHIFT, down, exec, brightnessctl set 5%-

# Utils
bind = $mainMod SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy
bind = $mainMod SHIFT, P, exec, toggle-bluetooth-device 98:DD:60:E6:ED:52
bind = $mainMod, Space, exec, hyprctl switchxkblayout at-translated-set-2-keyboard next

# In-workspace window control
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r
bindm = $mainMod, mouse:272, movewindow     # LMB

# Switch workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
