preload = /usr/share/backgrounds/Kurs_Space_Nord.png
preload = /usr/share/backgrounds/Kurs_Space.jpg
preload = /usr/share/backgrounds/IGN_Astronaut_Nord.png

wallpaper = eDP-1,/usr/share/backgrounds/IGN_Astronaut_Nord.png

