preload = /usr/share/backgrounds/Kurs_Space_Nord.png
preload = /usr/share/backgrounds/Kurs_Space.jpg
preload = /usr/share/backgrounds/IGN_Astronaut_Nord.png

# Catppuccin Mocha
preload = /usr/share/backgrounds/Street.jpg
preload = /usr/share/backgrounds/cat-waves.png
preload = /usr/share/backgrounds/car_cabin.jpg
preload = /usr/share/backgrounds/cut_rainbow.png
preload = /usr/share/backgrounds/Bridge.jpg
preload = /usr/share/backgrounds/michal-kvac-torii-rox-small.jpg
preload = /usr/share/backgrounds/bkg3.png
preload = /usr/share/backgrounds/flamingo.png
preload = /usr/share/backgrounds/japanese-hd-houses-and-shop-pgpqc22js1efc35z.jpg

wallpaper = eDP-1,/usr/share/backgrounds/cut_rainbow.png
