source = ../themes/mocha.conf

exec-once = waybar --config ~/.config/waybar/configs/hypr --style ~/.config/waybar/styles/blocky-solid-hyprland.css

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 2
    col.active_border = $surface0
    col.inactive_border = $mantle
}

decoration {
    rounding = 0
    blur = no
}

animations {
    enabled = no
}
