source = ../themes/mocha.conf

exec-once = waybar --config ~/.config/waybar/configs/hypr --style ~/.config/waybar/styles/floating-rounded.css

general {
    gaps_in = 5
    gaps_out = 20
    border_size = 4
    col.active_border = $base
    col.inactive_border = $base
}

decoration {
    rounding = 5
    blur = yes
    blur_size = 5
    blur_passes = 1
    blur_new_optimizations = on
    inactive_opacity = 0.9

    drop_shadow = no
    shadow_range = 20
    shadow_render_power = 100
    col.shadow = $overlay0
    col.shadow_inactive = $base
    shadow_ignore_window = yes
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}
