"$schema" = 'https://starship.rs/config-schema.json'

command_timeout=1000

[hostname]
ssh_only = false
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
disabled = false

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[git_status]
disabled = true

[lua]
disabled = true

[python]
disabled = true
