#!/usr/bin/env zsh

if [[ $THEME_STYLE == "light" ]]; then
    tmux set -g @nova-pane-active-border-style "#2848a9"
    tmux set -g @nova-pane-border-style "#643f61"
    tmux set -g @nova-status-style-bg "#e4dcd4"
    tmux set -g @nova-status-style-fg "#643f61"
    tmux set -g @nova-status-style-active-bg "#643f61"
    tmux set -g @nova-status-style-active-fg "#e4dcd4"
    tmux set -g @nova-status-style-double-bg "#e4dcd4"
    tmux set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #(basename #{pane_current_path}):#W"
    tmux set -g @nova-segment-mode "#{?client_prefix,Ω,ω}"
    tmux set -g @nova-segment-mode-colors "#2848a9 #e4dcd4"
    tmux set -g @nova-segment-whoami "#(whoami)@#h"
    tmux set -g @nova-segment-whoami-colors "#2848a9 #e4dcd4"
    tmux set -g @nova-segment-session "#S"
    tmux set -g @nova-segment-session-colors "#2848a9 #e4dcd4"
    tmux set -g @nova-segment-selector "#P:#F"
    tmux set -g @nova-segment-selector-colors "#2848a9 #e4dcd4"
    tmux set -g @nova-segment-gap "z"
    tmux set -g @nova-segment-gap-colors "#e4dcd4 #e4dcd4"
    tmux set -g @nova-rows 0
    tmux set -g @nova-segments-0-left "mode"
    tmux set -g @nova-segments-0-right "gap selector session whoami"
else
    tmux set -g @nova-pane-active-border-style "#44475a"
    tmux set -g @nova-pane-border-style "#282a36"
    tmux set -g @nova-status-style-bg "#121212"
    tmux set -g @nova-status-style-fg "#f2f4f8"
    tmux set -g @nova-status-style-active-bg "#78A9FF"
    tmux set -g @nova-status-style-active-fg "#121212"
    tmux set -g @nova-status-style-double-bg "#121212"
    tmux set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #(basename #{pane_current_path}):#W"
    tmux set -g @nova-segment-mode "#{?client_prefix,Ω,ω}"
    tmux set -g @nova-segment-mode-colors "#78A9FF #121212"
    tmux set -g @nova-segment-whoami "#(whoami)@#h"
    tmux set -g @nova-segment-whoami-colors "#78A9FF #121212"
    tmux set -g @nova-segment-session "#S"
    tmux set -g @nova-segment-session-colors "#78A9FF #121212"
    tmux set -g @nova-segment-selector "#P:#F"
    tmux set -g @nova-segment-selector-colors "#78A9FF #121212"
    tmux set -g @nova-segment-gap "z"
    tmux set -g @nova-segment-gap-colors "#121212 #121212"
    tmux set -g @nova-rows 0
    tmux set -g @nova-segments-0-left "mode"
    tmux set -g @nova-segments-0-right "gap selector session whoami"
fi
